require("settings") 
require("mappings")
require("plugins")
require("plugins_config.nvim_tree")
require("plugins_config.lualine")
require("plugins_config.bufferline")
require("plugins_config.nightfox")
require("plugins_config.alpha")
require("plugins_config.lsp")
require("plugins_config.alternate")
require("plugins_config.autopairs")
require("plugins_config.comment")
require("plugins_config.gitsigns")

